### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/Scraper#13]
How many pages scraped?
How many DataCatalogs? etc

**Comment by AlasdairGray** [comment]
Ideally this page would replace the [live deploys](https://biosschemas.org/liveDeploys) page.

**Comment by kcmcleod** [comment]
Current draft:
https://lxbisel.macs.hw.ac.uk:8080/EE-WebApp/stats

Not pretty. Needs sorting. Perhaps a pie chart?
Possibly a list of top level URLS?

**Comment by AlasdairGray** [comment]
Probably want some high level stats, e.g. number of resources (databases), number of pages, number of pages by type. I'm not sure that the number of triples is that meaningful.

For the by type we may want to focus the list to Bioschemas types of interest, i.e. omit blog.

Probably no need to show the full URLs of types, just their hyperlinked names would suffice. Can we order the types by their name or even let the user dynamically sort by name or size.

We possibly want some ways of doing into which resources have been marked up with which types and then links to structured testing tool for an example page, similar to the live deploys page. We want to make it easy for people to get to the markup of a resource so they can copy and hack it to their needs.

We could also have some way of getting a list of all URLs that been indexed.

http://www.macs.hw.ac.uk/~ajg33

________________________________

**Comment by AlasdairGray** [comment]
Stats page is returning an error
<img width="766" alt="Screen Shot 2019-08-30 at 14 02 21" src="https://user-images.githubusercontent.com/1141265/64022797-dee51500-cb2e-11e9-82e6-eef1770be9dc.png">

**Comment by kcmcleod** [comment]
```
2019/09/03 09:16:08 [error] 3384#0: *2073 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 137.195.27.39, server: lxbisel.macs.hw.ac.uk, request: "GET /EE-WebApp/stats HTTP/1.1", upstream: "http://127.0.0.1:8081/EE-WebApp/stats", host: "lxbisel.macs.hw.ac.uk:8080", referrer: "https://github.com/HW-SWeL/Scraper/issues/13"
```

**Comment by kcmcleod** [comment]
> Stats page is returning an error

Need to pre calculate answers in a summary graph. 

> For the by type we may want to focus the list to Bioschemas types of interest, i.e. omit blog.

Done.

> Probably no need to show the full URLs of types, just their hyperlinked names would suffice

Done

> Can we order the types by their name or even let the user dynamically sort by name or size.

That should be easy. *should* because I'm fighting virtuoso which doesn't seem to work on mac due to a kernel error: 'Server is out of memory and should be killed to prevent data corruption'.
This is questionable as top suggests there is 2GB free and I have min settings on which should use far less than 2GB.

> We possibly want some ways of doing into which resources have been marked up with which types and then links to structured testing tool for an example page, similar to the live deploys page. We want to make it easy for people to get to the markup of a resource so they can copy and hack it to their needs.

Search by type? Or do you mean something more complex?
Making it easy to copy markup may have issues. Firstly you propagate junk. Secondly, copyright.

> We could also have some way of getting a list of all URLs that been indexed.

If you mean sites OK. If you actually mean URLs I imagine that is way too slow...

**Comment by kcmcleod** [comment]
> We possibly want some ways of doing into which resources have been marked up with which types and then links to structured testing tool for an example page, similar to the live deploys page. We want to make it easy for people to get to the markup of a resource so they can copy and hack it to their needs.

Moving this into a [new issue](https://github.com/HW-SWeL/Scraper/issues/45), as rest done
