### ISSUE TITLE
Bigger triplestore

### ISSUE THREAD

**Issue by kcmcleod** [HW-SWeL/Scraper#3]
RDF4J handles ~100 million triples, but that is tiny when considering the size of biosamples & uniprot.

**Comment by AlasdairGray** [comment]
Other options would be 
- Blazegraph: used by Wikidata
- Virtuoso: used by DBpedia

**Comment by kcmcleod** [comment]
Also cannot properly secure rdf4j; can secure workbench but not underlying server.

**Comment by kcmcleod** [comment]
Related to size/number of triples. UniProt pages (looked at so far) have an average of over 800 triples per page.

**Comment by kcmcleod** [comment]
Virtuoso does not look like fun:
http://vos.openlinksw.com/owiki/wiki/VOS/VOSCentosNotes

Blazegraph:
doesnt seem to run on mac, but apparently works on linux

Both will need port forwarding...

**Comment by kcmcleod** [comment]
cant find user management functionality in blazegraph docs: https://wiki.blazegraph.com/wiki/index.php

**Comment by AlasdairGray** [comment]
Angus and Imran both have recent experience with installing Virtuoso.

**Comment by kcmcleod** [comment]
Done:
1. Installed virtuoso by compiling from source.
2. Loaded nq thru bulk loader.
3. Can see triples thru /sparql.

Still to do:
1. Programmatically access triplestore
2. Update data access layer to use virtuoso
3. Deploy access layer to both scraper & web app

**Comment by kcmcleod** [comment]
Both test & prod using virtuoso
